describe('BitmamaWeb', function()
{
    it('SignUp', function()
    {
        cy.visit("https://changera-business-staging.web.app/")
        cy.get('.font-bold > a').click()
        cy.get("input[placeholder='First Name']").type("Naomi");
        //cy.get(':nth-child(1) > .chakra-input__group > .chakra-input').type('Naomi')
        cy.get(':nth-child(2) > .chakra-input__group > .chakra-input').type('Dickson')
        cy.get(':nth-child(3) > .chakra-input__group > .chakra-input').type('Nneoma')
        cy.get(':nth-child(4) > .chakra-input__group > .chakra-input').type('naomi12@yahoo.com')
        cy.get('.PhoneInputInput').type(8133824118)
        cy.get('.chakra-select').select('Nigeria')
        cy.get(':nth-child(7) > .chakra-input__group > .chakra-input').type('Password@123')
        cy.get(':nth-child(9) > .chakra-input__group > .chakra-input').type('Password@123')
        cy.get('.chakra-button > .flex').click()
        //cy.get('#root > div:nth-child(2) > div > div > div.w-full.px-2.py-6.overflow-y-auto.mdx\:py-16.mdx\:px-16.bg-primary-600 > div > div.flex.items-center.justify-center.w-full.mt-8.overflow-y-visible.mdx\:mt-12 > div').contains('To secure your account, please complete the following verifcation')
        cy.get(':nth-child(1) > .flex-col > .chakra-button').click()
        cy.get('.css-17d7hau').click()
        cy.get('.mt-4 > .bg-primary-600').click()
        cy.get('#pin-input-\:r4\:-0').click().type(0)
        cy.get('#pin-input-\:r4\:-1').click().type(0)
        cy.get('#pin-input-\:r4\:-2').click().type(0)
        cy.get('#pin-input-\:r4\:-3').click().type(0)
        cy.get('#pin-input-\:r4\:-4').click().type(0)
        cy.get('#pin-input-\:r4\:-5').click().type(0) 
        
    })
})